<a href="https://colab.research.google.com/github/RebuildYY/sp20161624/blob/master/p4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

def max(a, b, c, d):
  max = a
  if max < b:
    max = b
  if max < c:
    max = c
  if max < d:
    max = d
  return max

print("Input:")
n = int(input())
if n % 2 != 0:
  print("짝수를 입력해주세요.")

else:
  A = np.random.random((n,n))
  B = np.random.random((int(n/2), int(n/2)))
  for i in range(0, n):
    for j in range(0, n):
      A[i][j] = round(A[i][j], 2)
  
  for i in range(0, n, 2):
    for j in range(0, n, 2):
      B[int(i/2)][int(j/2)] = max(A[i][j], A[i][j+1], A[i+1][j], A[i+1][j+1])
  
  print("Output:")
  print(A)
  print(B)

Input:
4
Output:
[[0.61 0.08 0.4  0.75]
 [0.82 0.85 0.06 0.45]
 [0.26 0.59 0.14 0.45]
 [0.29 0.27 0.6  0.65]]
[[0.85 0.75]
 [0.59 0.65]]
